-- ============================================================================
-- Cadence Scores Database — US Region
-- Generated: 2026-06-16T07:47:06.318Z
-- Feeds the in-game LFG / group finder overlay.
-- DO NOT EDIT — this file is auto-generated by the Cadence server.
-- ============================================================================

CADENCE_SCORES_REGION = "us"
CADENCE_SCORES_GENERATED = 1781596026
CADENCE_SCORES_VERSION = 1

CadenceScoresDB_us = {
["Gruffles-Spirestone"]={s=86,r=86,n=4,rn=4,ro="H",cl="DRUID",c=2},
["Vitalithry-Stormscale"]={s=82,m=84,r=82,n=5,mn=1,rn=4,ro="D",cl="EVOKER",c=2},
["Mcversatile-Stormscale"]={s=78,r=78,n=4,rn=4,ro="T",cl="DRUID",c=2},
["Båne-Spirestone"]={s=76,r=76,n=4,rn=4,ro="D",cl="DEMONHUNTER",c=2},
["Imbria-Spirestone"]={s=76,r=76,n=4,rn=4,ro="D",cl="DRUID",c=2},
["Womann-Thrall"]={s=75,r=75,n=4,rn=4,ro="D",cl="PALADIN",c=2},
["Paladín-Stormscale"]={s=68,r=68,n=4,rn=4,ro="T",cl="PALADIN",c=2},
["Shadowfawn-Stormscale"]={s=66,r=66,n=4,rn=4,ro="D",cl="PRIEST",c=2},
["Dunhambones-Stormscale"]={s=66,r=66,n=4,rn=4,ro="D",cl="DEATHKNIGHT",c=2},
["Imrah-Stormscale"]={s=61,r=61,n=4,rn=4,ro="H",cl="MONK",c=2},
["Avãcyn-Spirestone"]={s=52,r=52,n=4,rn=4,ro="D",cl="WARRIOR",c=2},
}
