-- ============================================================================
-- Cadence Scores Database — EU Region
-- Generated: 2026-06-02T07:28:14.262Z
-- Feeds the in-game LFG / group finder overlay.
-- DO NOT EDIT — this file is auto-generated by the Cadence server.
-- ============================================================================

CADENCE_SCORES_REGION = "eu"
CADENCE_SCORES_GENERATED = 1780385294
CADENCE_SCORES_VERSION = 1

CadenceScoresDB_eu = {
["Tamako-Kult der Verdammten"]={s=97,m=97,n=11,mn=11,ro="H",cl="PRIEST",c=3},
["Ventrix-Kult der Verdammten"]={s=97,m=97,n=20,mn=20,ro="T",cl="MONK",c=4},
["Faramip-Antonidas"]={s=96,m=96,n=20,mn=20,ro="H",cl="PRIEST",c=4},
["Faramirg-Antonidas"]={s=96,m=96,n=24,mn=24,ro="D",cl="ROGUE",c=4},
["Jihadjo-Kazzak"]={s=92,m=92,n=4,mn=4,ro="D",cl="DEMONHUNTER",c=2},
["Bollkar-Kult der Verdammten"]={s=91,m=91,n=3,mn=3,ro="T",cl="DRUID",c=2},
["Frior-Kult der Verdammten"]={s=88,m=88,n=13,mn=13,ro="T",cl="DEATHKNIGHT",c=3},
["Òono-Tarren Mill"]={s=87,m=89,r=87,n=3,mn=1,rn=2,ro="H",cl="SHAMAN",c=2},
["Mindnbone-Ragnaros"]={s=81,m=81,n=4,mn=4,ro="D",cl="DEATHKNIGHT",c=2},
}
