-- ============================================================================
-- Cadence Scores Database — EU Region
-- Generated: 2026-05-30T06:54:00.298Z
-- Feeds the in-game LFG / group finder overlay.
-- DO NOT EDIT — this file is auto-generated by the Cadence server.
-- ============================================================================

CADENCE_SCORES_REGION = "eu"
CADENCE_SCORES_GENERATED = 1780124040
CADENCE_SCORES_VERSION = 1

CadenceScoresDB_eu = {
["Tamako-Kult der Verdammten"]={s=98,m=98,n=10,mn=10,ro="H",cl="PRIEST",c=3},
["Faramip-Antonidas"]={s=97,m=97,n=17,mn=17,ro="H",cl="PRIEST",c=4},
["Ventrix-Kult der Verdammten"]={s=97,m=97,n=19,mn=19,ro="T",cl="MONK",c=4},
["Faramirg-Antonidas"]={s=97,m=97,n=17,mn=17,ro="D",cl="ROGUE",c=4},
["Frior-Kult der Verdammten"]={s=93,m=93,n=8,mn=8,ro="T",cl="DEATHKNIGHT",c=3},
["Jihadjo-Kazzak"]={s=92,m=92,n=4,mn=4,ro="D",cl="DEMONHUNTER",c=2},
["Òono-Tarren Mill"]={s=87,m=89,r=87,n=3,mn=1,rn=2,ro="H",cl="SHAMAN",c=2},
["Mindnbone-Ragnaros"]={s=81,m=81,n=4,mn=4,ro="D",cl="DEATHKNIGHT",c=2},
}
