-- ============================================================================
-- Cadence Scores Database — KR Region
-- Generated: 2026-08-25T06:04:56.648Z
-- Feeds the in-game LFG / group finder overlay.
-- DO NOT EDIT — this file is auto-generated by the Cadence server.
-- ============================================================================

CADENCE_SCORES_REGION = "kr"
CADENCE_SCORES_GENERATED = 1787637896
CADENCE_SCORES_VERSION = 1

CadenceScoresDB_kr = {
}
