-- ============================================================================
-- Cadence Scores Database — KR Region
-- Generated: 2026-08-12T06:24:15.712Z
-- Feeds the in-game LFG / group finder overlay.
-- DO NOT EDIT — this file is auto-generated by the Cadence server.
-- ============================================================================

CADENCE_SCORES_REGION = "kr"
CADENCE_SCORES_GENERATED = 1786515855
CADENCE_SCORES_VERSION = 1

CadenceScoresDB_kr = {
}
