-- ============================================================================
-- Cadence Scores Database — TW Region
-- Generated: 2026-09-29T06:00:53.516Z
-- Feeds the in-game LFG / group finder overlay.
-- DO NOT EDIT — this file is auto-generated by the Cadence server.
-- ============================================================================

CADENCE_SCORES_REGION = "tw"
CADENCE_SCORES_GENERATED = 1790661653
CADENCE_SCORES_VERSION = 1

CadenceScoresDB_tw = {
}
