-- ============================================================================
-- Cadence Scores Database — KR Region
-- Generated: 2026-09-27T18:00:24.544Z
-- Feeds the in-game LFG / group finder overlay.
-- DO NOT EDIT — this file is auto-generated by the Cadence server.
-- ============================================================================

CADENCE_SCORES_REGION = "kr"
CADENCE_SCORES_GENERATED = 1790532024
CADENCE_SCORES_VERSION = 1

CadenceScoresDB_kr = {
}
