-- ============================================================================
-- Cadence Scores Database — US Region
-- Generated: 2026-05-30T06:53:59.894Z
-- Feeds the in-game LFG / group finder overlay.
-- DO NOT EDIT — this file is auto-generated by the Cadence server.
-- ============================================================================

CADENCE_SCORES_REGION = "us"
CADENCE_SCORES_GENERATED = 1780124039
CADENCE_SCORES_VERSION = 1

CadenceScoresDB_us = {
}
