-- ============================================================================
-- Cadence Scores Database — EU Region
-- Generated: 2026-06-24T07:02:46.383Z
-- Feeds the in-game LFG / group finder overlay.
-- DO NOT EDIT — this file is auto-generated by the Cadence server.
-- ============================================================================

CADENCE_SCORES_REGION = "eu"
CADENCE_SCORES_GENERATED = 1782284566
CADENCE_SCORES_VERSION = 1

CadenceScoresDB_eu = {
["Faramirg-Antonidas"]={s=96,m=96,n=24,mn=24,ro="D",cl="ROGUE",c=4},
["Ventrix-Kult der Verdammten"]={s=96,m=96,n=23,mn=23,ro="T",cl="MONK",c=4},
["Tamako-Kult der Verdammten"]={s=95,m=95,n=17,mn=17,ro="H",cl="PRIEST",c=4},
["Faramip-Antonidas"]={s=95,m=95,n=32,mn=32,ro="H",cl="PRIEST",c=5},
["Jihadjo-Kazzak"]={s=92,m=92,n=4,mn=4,ro="D",cl="DEMONHUNTER",c=2},
["Bollkar-Kult der Verdammten"]={s=91,m=91,n=3,mn=3,ro="T",cl="DRUID",c=2},
["Ysondrê-Kult der Verdammten"]={s=89,m=89,n=11,mn=11,ro="D",cl="HUNTER",c=3},
["Òono-Tarren Mill"]={s=87,m=89,r=87,n=3,mn=1,rn=2,ro="H",cl="SHAMAN",c=2},
["Frior-Kult der Verdammten"]={s=87,m=87,n=26,mn=26,ro="T",cl="DEATHKNIGHT",c=4},
["Mindnbone-Ragnaros"]={s=81,m=81,n=4,mn=4,ro="D",cl="DEATHKNIGHT",c=2},
}
