-- ============================================================================
-- Cadence Scores Database — TW Region
-- Generated: 2026-06-05T07:19:58.943Z
-- Feeds the in-game LFG / group finder overlay.
-- DO NOT EDIT — this file is auto-generated by the Cadence server.
-- ============================================================================

CADENCE_SCORES_REGION = "tw"
CADENCE_SCORES_GENERATED = 1780643998
CADENCE_SCORES_VERSION = 1

CadenceScoresDB_tw = {
}
