-- ============================================================================
-- Cadence Scores Database — TW Region
-- Generated: 2026-06-12T07:28:08.583Z
-- Feeds the in-game LFG / group finder overlay.
-- DO NOT EDIT — this file is auto-generated by the Cadence server.
-- ============================================================================

CADENCE_SCORES_REGION = "tw"
CADENCE_SCORES_GENERATED = 1781249288
CADENCE_SCORES_VERSION = 1

CadenceScoresDB_tw = {
}
