-- ============================================================================
-- Cadence Scores Database — US Region
-- Generated: 2026-06-03T07:31:32.494Z
-- Feeds the in-game LFG / group finder overlay.
-- DO NOT EDIT — this file is auto-generated by the Cadence server.
-- ============================================================================

CADENCE_SCORES_REGION = "us"
CADENCE_SCORES_GENERATED = 1780471892
CADENCE_SCORES_VERSION = 1

CadenceScoresDB_us = {
}
